-- Agregar columnas nuevas a Users
ALTER TABLE Users ADD COLUMN IF NOT EXISTS lastName2 VARCHAR(100) DEFAULT NULL;
ALTER TABLE Users ADD COLUMN IF NOT EXISTS country VARCHAR(10) DEFAULT 'MX';
ALTER TABLE Users ADD COLUMN IF NOT EXISTS state VARCHAR(100) DEFAULT NULL;
ALTER TABLE Users MODIFY phone VARCHAR(50);
